# Create tag based Vmware protection group.
---
- name: Create tag based Vmware protection group
  hosts: workstation
  gather_facts: false
  tasks:
    - name: Update Vmware Protection job with virtual machines.
      cohesity.dataprotect.cohesity_job:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: "present"
        job_name: "protect_vm"
        policy: Gold
        storage_domain: "DefaultStorageDomain"
        sources:
          - endpoint: "vcenter.domain.com"
        environment: "VMware"
        include_tags:
          - TagCategoryName:
              - Tag1
              - Tag2
          - TagCategoryName3:
              - Tag3
            TagCategoryName2:
              - Tag4
        time_zone: "America/Los_Angeles"
        start_time: "00:00"
