# => Create/Update a new Vmware protection job for list of Sources.
---
- hosts: workstation
  gather_facts: false
  collections:
    - cohesity.dataprotect
  tasks:
    - name: Create Vmware Protection job.
      cohesity_job:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: "present"
        job_name: "protect_vm_5"
        policy: Gold
        storage_domain: "DefaultStorageDomain"
        sources:
          - endpoint: "vcenter.domain.com"
        environment: "VMware"
        include:
          - automation_vm_1-KsZ4
          - CentOS-Default
        exclude:
          - WindowsServer
        # Enabling append_to_existing will add the new list of VMs to the
        # existing vms available in the job.
        # append_to_existing: true
        cancel_active: true
        time_zone: "America/Los_Angeles"
        start_time: "00:00"
