# => Create/Update a new Vmware protection job for list of Sources.
---
- name: Create/Update a new Vmware protection job for list of Sources
  hosts: workstation
  gather_facts: false
  tasks:
    - name: Create Vmware Protection job.
      cohesity.dataprotect.cohesity_job:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: "present"
        job_name: "protect_vm_5"
        policy: Gold
        storage_domain: "DefaultStorageDomain"
        sources:
          - endpoint: "vcenter.domain.com"
        environment: "VMware"
        include:
          - automation_vm_1-KsZ4
          - CentOS-Default
        exclude:
          - WindowsServer
        time_zone: "America/Los_Angeles"
        start_time: "00:00"
