# => Update a Vmware protection job for list of Sources.
---
- name: Update a Vmware protection job for list of Sources
  hosts: workstation
  gather_facts: false
  tasks:
    - name: Update Vmware Protection job with virtual machines.
      cohesity.dataprotect.cohesity_job:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: "present"
        job_name: "protect_vm"
        sources:
          - endpoint: "vcenter.domain.com"
        environment: "VMware"
        # Following list of of virtual machines, will be added to the
        # existing job.
        include:
          - automation_vm_1-KsZ4
          - CentOS-Default
        # List of tags in include_tags will be added to the job.
        include_tags:
          - StorageBasedTags: # Tag Category Name
              - Tag1 # Tag Name
              - Tag2 # Tag Name
          - CustomStorageTagCategory:
              - Tag3 # Tag Name
            StorageBasedTags:
              - Tag4 # Tag Name
        # Following list of tags in exclude_tags will be excluded from the job.
        exclude_tags:
          - TagCategory: # Tag Category Name
              - Tag
        # Enabling append_to_existing will add the new list of VMs to existing
        # VMs, and add new list of tags to the existing tags available in the
        # job.
        append_to_existing: true
