# Playbook to refresh list of Physical source to the cluster.
# If the list of sources to be registered is available in the inventory
# as groups we can access them as follows.
# with_items: "{{ groups['linux'] }}"

---
- hosts: localhost
  become: false
  collections:
    - cohesity.dataprotect
  vars:
    linux_servers:
      - ServerA
      - ServerB
  tasks:
    - name: "Cohesity Protection Source: Refresh list of Sources"
      cohesity_source:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: present
        endpoint: "{{ item }}"
        environment: "Physical"
        refresh: true
      with_items: "{{ linux_servers }}"
