# Playbook to register Physical source to the cluster.
---
- name: Playbook to register Physical source to the cluster
  hosts: localhost
  become: false
  tasks:
    - name: "Cohesity Protection Source: Set Source to state of present"
      cohesity.dataprotect.cohesity_source:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: present
        endpoint: 192.168.1.1
        environment: "Physical"
        force_register: true
