# => Collection: cohesity.dataprotect
# =>
# => Stop a running protection job.
---
- name: Stop a running protection job
  hosts: workstation
  gather_facts: false
  tasks:
    - name: Stop Protection job
      cohesity.dataprotect.cohesity_job:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: "stopped"
        name: "DeleteJob"
        cancel_active: true
        environment: "VMware"
