# => Cohesity Agent Management
# =>
# => Collection: cohesity.dataprotect
# =>

# => Install the Cohesity Datastore Agent on each Postgresql Centos host
# => specified in the Ansible inventory
# =>
---
- name: Install the Cohesity Datastore Agent on each Postgresql Centos host
  hosts: postgresql
  # => We need to gather facts to determine the OS type of
  # => the machine
  gather_facts: true
  become: true
  tasks:
    - name: Check if firewall is enabled on CentOS or RedHat
      ansible.builtin.command: "firewall-cmd --state"
      ignore_errors: true
      register: firewall_status_centos
      changed_when: false
      when:
        - ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
      tags: always

    - name: "Cohesity agent: Set Agent to state of {{ state | default('present') }}"
      cohesity.dataprotect.cohesity_plugin:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: "{{ state | default('present') }}"
        platform: "PostgreSQL"
