# => Cohesity Agent Management
# =>
# => Collection: cohesity.dataprotect
# =>

# => Install the Cohesity Datastore Agent on each SapHana host
# => specified in the Ansible inventory
# =>
---
- name: Install the Cohesity Datastore Agent on each SapHana host
  hosts: saphana
  # => We need to gather facts to determine the OS type of
  # => the machine
  gather_facts: true
  vars:
    state: "present"
    platform: SapHana
    sap_hana_user: sss_admin
    sap_hana_password: password
    sap_hana_home: /usr/sap/ABC/home
    sid: ABC
    user_store_key: KEY
  tasks:
    - name: Check if firewall is enabled on CentOS or RedHat
      ansible.builtin.command: "firewall-cmd --state"
      ignore_errors: true
      register: firewall_status
      changed_when: false
      when:
        - ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "SLES"
      tags: always

    - name: Enable tcp port 11113 for CentOS or RedHat
      ansible.builtin.command: "firewall-cmd {{ item }}"
      with_items:
        - --zone=public --permanent --add-port 11113/tcp
        - --reload
      changed_when: "'success' in ansible_facts.stdout"
      when:
        - ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "SLES"
        - firewall_status.rc == 0
      tags: always

    - name: "Cohesity agent: Set Agent to state of {{ state | default('present') }}"
      cohesity.dataprotect.cohesity_plugin:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: "{{ state | default('present') }}"
        platform: "SapHana"
        endpoint: "{{ inventory_hostname }}"
        download_location: "{{ sap_hana_home }}"
        netmask_bits: 20
      register: result
      when: state == "present" and platform == "SapHana"

    - name: "Install the Cohesity UDA connector plugin"
      ansible.builtin.shell: >
        set -o pipefail && echo {{ sap_hana_password }} | su - {{ sap_hana_user }} -c '
        {{ result.filename }}  -- -i -s {{ sid }} -k {{ user_store_key }}
        -w uda -a {{ cohesity_server }} -d {{ sap_hana_home }} -y'
      when: state == "present" and platform == "SapHana"
      changed_when: true

    - name: "Creation soft link to /opt/cohesity/agent/uda_scripts path"
      ansible.builtin.command: "ln -s /usr/sap/SSS/home/cohesity_backint_plugin/uda_scripts /opt/cohesity/agent/uda_scripts"
      when: state == "present" and platform == "SapHana"
      changed_when: true

    - name: "UDA scripts will be available in {{ sap_hana_home }}/cohesity_backint_plugin/uda_scripts"
      when: state == "present" and platform == "SapHana"
      ansible.builtin.command: ls  /opt/cohesity/agent
      changed_when: false
