# => Playbook to Create a new Protection View.
---
- name: Playbook to Create a new Protection View
  hosts: workstation
  gather_facts: false
  vars:
    view_name: ViewName
    state: present
  tasks:
    - name: "Cohesity view: Set state to present for {{ view_name }}"
      cohesity.dataprotect.cohesity_view:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        state: "{{ state | default('present') }}"
        name: "s3-view"
        description: "View is created using Ansible"
        storage_domain: "DefaultStorageDomain"
        qos_policy: "Backup Target Low"
        protocol: "All"
        case_insensitive: false
        inline_dedupe_compression: false
        security:
          security_mode: "NativeMode"
          override_global_whitelist:
          whitelist:
            subnet_ip:
            subnet_mask:
            nfs_permission:
            smb_permission:
            nfs_root_squash:
            smb_root_squash:
        quota:
          set_logical_quota:
          hard_limit_bytes:
          set_alert_threshold:
          alert_limit_bytes:
        nfs_options:
          user_id:
          group_id:
        smb_options:
          view_discovery:
          access_based_enumeration:
