# => Playbook to delete a View.
---
- name: Playbook to delete a View
  hosts: workstation
  gather_facts: false
  vars:
    view_name: ViewName
    domain: DefaultStorageDomain
  tasks:
    - name: "Cohesity view: Set state to absent for {{ view_name }}"
      cohesity.dataprotect.cohesity_view:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        state: "absent"
        name: "{{ view_name }}"
        case_insensitive: true
        storage_domain: "{{ domain }}"
