# Playbook to recover Oracle database from the cluster.
---
- name: Playbook to recover Oracle database from the cluster
  hosts: localhost
  become: false

  vars:
    oracle_source_type: standalone
    oracle_target_server: "{{ scan_vip_address if oracle_source_type == 'rac' else oracle_endpoint }}"

  tasks:
    - name: "Cohesity Oracle Restore Task: Set Source to state of present"
      cohesity.dataprotect.cohesity_oracle_restore:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: present
        source_type: "{{ oracle_source_type }}"
        source_db: "{{ oracle_source_db }}"
        task_name: "{{ oracle_task_name }}"
        source_server: "{{ scan_vip_address if oracle_source_type == 'rac' else oracle_endpoint }}"
        target_server: "{{ oracle_target_server }}"
        target_db: "{{ oracle_target_db }}"
        oracle_home: "{{ oracle_home }}"
        oracle_base: "{{ oracle_base }}"
        oracle_data: "{{ oracle_data }}"
